### ISSUE TITLE
I don't get the server side part.

### ISSUE THREAD

**Issue by reggi** [thlorenz/bromote#4]
I just wanna define a script url and export shim and get a callback / have it there when I need it. I don't really understand bromote, and I really want to.

**Comment by johnkpaul** [comment]
@reggi The "Server side part" you're talking about is the browserify bundling code for your build script. Right now, in your google-maps-browserify repo example, you're using the command line tool but AFAIK, to use bromote, you will need to use a build script that uses the browserify API.

**Comment by reggi** [comment]
@johnkpaul ok so it's not a server side script, it's a build script that replaces the command line tool, got it. Thanks for the explanation!
