### ISSUE TITLE
Google Maps failing to load it's deps to the dom?

### ISSUE THREAD

**Issue by reggi** [thlorenz/bromote#5]
Here's a shot of the initial google maps api loading, but it's not loading any of the other deps. 

![screenshot](https://api.monosnap.com/image/download?id=lQCcPMzoFkRWJYQkpjiquHTpuW0qFr) of 

Here's a shot of the console, `Uncaught TypeError: Cannot read property 'maps' of undefined`.

![shot](https://f.cloud.github.com/assets/296798/2422901/a33f1228-ab93-11e3-854a-5fd40a089139.png) 

Made a [new branch](https://github.com/reggi/google-maps-browserify/tree/bromote-gmaps) to show for this, fyi it's not visible on gh-pages.

**Comment by thlorenz** [comment]
It's hard to tell why this is not working for you.
@toddself succeeded in doing something very similar and maybe able to help.

**Comment by thlorenz** [comment]
Any news on this? @toddself do you have any feedback on why this isn't working [as implemented](https://github.com/reggi/google-maps-browserify/tree/bromote-gmaps)?

**Comment by reggi** [comment]
Haven't had time to get into it lately @thlorenz -_-

**Comment by toddself** [comment]
@reggi it looks like you're trying to shim it via requirejs first? That might be the problem.

You need to provide bromote with the google maps script directly.  Usually I hate pointing to tests as an example, but this should get you started: https://github.com/thlorenz/bromote/blob/master/test/jsonp-callbacks/build.js#L13

**Comment by reggi** [comment]
@toddself I'll try take a look at this later tonight, and get back to you so @thlorenz can close this ticket. Thanks a million! :+1:

**Comment by thlorenz** [comment]
Closing this since seems to not be an actual bromote issue.
