### ISSUE TITLE
Can't load jquery without bromote?

### ISSUE THREAD

**Issue by reggi** [thlorenz/bromote#6]
Whis is this giving me a `Uncaught ReferenceError: $ is not defined`?

```
var bromote = require('bromote');
var jquery = require("jquery");

$(document).ready(function() {
    bromote.google(function(google) {
        var map = new google.maps.Map(document.getElementById('map-canvas'), {
            zoom: 11,
            center: new google.maps.LatLng(40.670287895547006, -73.9865255355835)
        });
    });
});
```

Here's the [branch](https://github.com/reggi/google-maps-browserify/tree/bromote-jquery) that demos this.

**Comment by thlorenz** [comment]
I'm not sure what you are doing here, looks like you are mixing bromote with some other shim?
Have a look at browserify-shim to get properly loaded and or do `window.$ = jquery` since whatever you are loading afterwards seems to expect it to be there.

**Comment by reggi** [comment]
@thlorenz I'm using normal browserify, you can't use both?

**Comment by thlorenz** [comment]
bromote is meant to work with browserify, but I'm not sure how you expect jquery to be requireable (unless you installed it via npm).

Best is if you could create a small repro that I can have a look at to help.

**Comment by reggi** [comment]
Yeah, I did install it via NPM. Oh, I thought you saw the repo I linked it up top [> > it's here < <](https://github.com/reggi/google-maps-browserify/tree/bromote-jquery).

**Comment by thlorenz** [comment]
I'm very confused about the repo you provided.
- it's using browserify-shim v2 - you should upgrade to v3 (but it doesn't use it anywhere, so why is it a dependency ?!?)
- it has a `requirejs.config` ?!?
- it depends on `jquery` via `npm` which is good, but has nothing to do with `bromote`

My only guess is that `google` expects `$` to be on the `window` and as I already suggested `window.$ =require('jquery')` may solve your problem. I mean that's exactly what your error indicates ;)

**Comment by thlorenz** [comment]
Closing this for now since this is not a `bromote` issue at all.

It's more of a 'how to use browserify' question, so feel free to find help in irc `#browserify`.
