### ISSUE TITLE
google maps undefined

### ISSUE THREAD

**Issue by sixtimes** [thlorenz/bromote#7]
I'm pretty sure I'm making a faulty assumption somewhere in here - could you point me in the right direction?

I'm using scripts from gulp-starter (https://github.com/greypants/gulp-starter) to build my browserify scripts. I've been trying to work bromote google maps into a version of https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/browserify.js. I trigger bromote.google_maps and arrive in the callback, but the data object returned is undefined. What am I doing wrong? Code below.

https://gist.github.com/sixtimes/7f7b1ba5eda2a97b5d25

**Comment by thlorenz** [comment]
@toddself you got this to work at some point right? Do you have any tips here?

**Comment by toddself** [comment]
Let me take a look at this.

**Comment by thlorenz** [comment]
Thanks, appreciated ;)

**Comment by toddself** [comment]
@sixtimes posted a question on your gist

**Comment by sixtimes** [comment]
@toddself answered it

**Comment by thlorenz** [comment]
ok seems like problem solved, thanks @toddself.
Closing.
